GHOST_PENALITY = -50
TIME_PENALITY = -1  ### -.01
GHOST_REWARD = 7.5

HIT_WALL_PENALITY = -3.5 
PELLET_REWARD = 20
POWERPELLET_REWARD = 60
FRUIT_REWARD = 200
FINISH_LEVEL_REWARD = 50

GHOST_UPDATE_REWARD = 0.5
GHOST_UPDATE_PENALITY = 2
