TIME_PENALITY = -0.5  ### -.01
RAND_PENALITY = -0.08    ## this will only be in the safe mode training once ghosts are in disable it
PELLET_LOST_PENALITY = -0.08
HIT_WALL_PENALITY = -3.5 

PELLET_REWARD_UPDATE = 0.02
PELLET_REWARD = 10
POWERPELLET_REWARD = 50
FRUIT_REWARD = 200
FINISH_LEVEL_REWARD = 500


GHOST_PENALITY = -50
GHOST_REWARD = 7.5
GHOST_UPDATE_REWARD = 0.5
GHOST_UPDATE_PENALITY = 2